basic:
  exp_name: dpo-weighted
  model_save_dir: ../../gail_torch/assets/learned_models
  expert_path: ../../gail_torch/assets/expert_traj/expert.pkl
  tb_log_dir: ../../gail_torch/assets/tblogs

env_specs:
  env_name: GridWorld-v0
  repeat_ratio: 1

exp_params:
  seed: 0
  memory_size: 20000
  update_timestep: 128
  num_updates: 50
  num_pretrain: 0
  num_threads: 1
  disc_lr: 0.0003
  state_only: true
  policy_params:
    sp_alpha: 0.1
    sp_lr: 0.003
    id_lr: 0.0001
    actor_lr: 0.0003

others:
  model_save_freq: 0
